
# Basic YAML configuration for Ubuntu

ubuntu_setup:
  name: basic-ubuntu-setup
  description: "Configuration for a basic Ubuntu setup"

packages:
  - update: true
  - upgrade: true
  - install:
      - apache2  # Installs Apache web server
      - git      # Installs Git version control
      - curl     # Installs cURL utility
      - ufw      # Installs Uncomplicated Firewall

commands:
  - enable_apache:
      command: "systemctl enable apache2"
  - start_apache:
      command: "systemctl start apache2"
  - configure_firewall:
      command: |
        ufw allow 'Apache'
        ufw enable
        ufw status

users:
  - username: admin
    groups:
      - sudo
    home_directory: /home/admin
    shell: /bin/bash

network:
  firewall:
    allow:
      - port: 22   # SSH
      - port: 80   # HTTP
      - port: 443  # HTTPS


